name: Sync PySpark Image to Huawei SWR

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Huawei SWR
        run: echo "${{ secrets.HUAWEI_SWR_PASSWORD }}" | docker login swr.cn-north-4.myhuaweicloud.com -u "${{ secrets.HUAWEI_SWR_USERNAME }}" --password-stdin

      - name: Pull PySpark image
        run: docker pull bitnami/spark:3.5.0

      - name: Tag for Huawei SWR
        run: docker tag bitnami/spark:3.5.0 swr.cn-north-4.myhuaweicloud.com/cloud-course-a/pyspark:3.5.0

      - name: Push to Huawei SWR
        run: docker push swr.cn-north-4.myhuaweicloud.com/cloud-course-a/pyspark:3.5.0
